INSERT INTO books (title, author, genre, out, image) VALUES ('Free the land', 'Edward Onaci', 'false', 'https://imgur.com/klIN2Fi');
INSERT INTO books (title, author, genre, out, image) VALUES ('Marcus Garvey and the Vision of Africa' 'John Henrik Clarke', 'false', 'https://imgur.com/afBF1X5');
INSERT INTO books (title, author, genre, out, image) VALUES ('Black Power', 'Kwame Ture and Charles V. Hamilton', 'false', 'https://imgur.com/MmhAJmX');
INSERT INTO books (title, author, genre, out, image) VALUES ('The Mis-Education of the Negro', 'Carter G. Woodson', 'false', 'https://imgur.com/dcKW7Wi');
INSERT INTO books (title, author, genre, out, image) VALUES ('Here I Stand', 'Paul Robeson', 'false', 'https://imgur.com/493XJmt');
INSERT INTO books (title, author, genre, out, image) VALUES ('Malcolm X Speaks', 'Malcolm X', 'false', 'https://imgur.com/DXMTlwZ');
INSERT INTO books (title, author, genre, out, image) VALUES ('Assata', 'Assata Shakur', 'false', 'https://imgur.com/LsCY8Le');
INSERT INTO books (title, author, genre, out, image) VALUES ('Independence Revolution in Portuguese-speaking and Africa', 'Marco Mondaini and Colin Darch', 'false', 'https://imgur.com/hnEsYZ0');
INSERT INTO books (title, author, genre, out, image) VALUES ('Black Radical the life and times of William Monroe Trotter', 'Kerri K. Greenidge', 'false', 'https://imgur.com/bTD55ls');
INSERT INTO books (title, author, genre, out, image) VALUES ('War and revolution Rethinking the 20th Century', 'Domenico Losurdo', 'false', 'https://imgur.com/ONK0tzP');
INSERT INTO books (title, author, genre, out, image) VALUES ('the Marx-Engles Reader', 'Robert C. Tucker', 'false', 'https://imgur.com/apHHro5');
INSERT INTO books (title, author, genre, out, image) VALUES ('The Descrution of Black Civilization', 'Chancellor Williams', 'false', 'https://imgur.com/4DYaJim');
INSERT INTO books (title, author, genre, out, image) VALUES ('Black Reconstruction in America', 'W.E.B.Du Bois', 'false', 'https://imgur.com/EBEfhiQ');
INSERT INTO books (title, author, genre, out, image) VALUES ('Paul Robeson the Artist Revolutionary', 'Gerald Horne', 'false', 'https://imgur.com/qDc42D6');